CREATE TABLE IF NOT EXISTS "admin" (
    id SERIAL PRIMARY KEY,
    admin_id VARCHAR(255) NOT NULL UNIQUE,
    fullname VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "categories" (
    id SERIAL PRIMARY KEY,
    category_name VARCHAR(255) NOT NULL,
    image VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "cakes" (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL, 
    price VARCHAR(255) NOT NULL,
    discount_price VARCHAR(255) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    categories VARCHAR(255) NOT NULL,
    image VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);